# Generated by Django 5.1.7 on 2025-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_deal_datetime_deal_description_deal_imgae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
