# Generated by Django 5.1.7 on 2025-03-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_dealitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='imgae',
            new_name='image',
        ),
    ]
