# Generated by Django 5.1.7 on 2025-03-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_imgae_deal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealitem',
            name='deal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.deal'),
        ),
    ]
