# Generated by Django 5.1.7 on 2025-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_dealitem_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='Lahore', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
