# Generated by Django 5.1.7 on 2025-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_branch_city_branch_country_alter_branch_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
