# Generated by Django 5.2 on 2025-05-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_branch_image_alter_deal_image_alter_menuitem_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'restaurant')},
        ),
    ]
